apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: roboshop
  name: roboshop-trainee-binding

subjects:
- kind: User
  name: jai
  apiGroup: rbac.authorization.k8s.io

roleRef:
  kind: Role
  name: roboshop-trainee
  apiGroup: rbac.authorization.k8s.io