apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::419142569809:role/eksctl-roboshop-nodegroup-spot-NodeInstanceRole-VrFx0hRwWLLq
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::419142569809:user/jai
      username: jai
      groups:
      - roboshop-trainee
    - userarn: arn:aws:iam::419142569809:user/kushi
      username: kushi
      groups:
      - roboshop-admin
kind: ConfigMap
metadata:
  creationTimestamp: "2026-07-27T10:06:26Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1179"
  uid: 15d82ceb-531b-4c5c-a4f2-cbf1176edf43
